disabled_rules:
  - trailing_whitespace
  - todo
  - force_cast
  - large_tuple
  - force_try
  - notification_center_detachment
excluded:
  - Pods

# Required rules

block_based_kvo:
  severity: error

class_delegate_protocol:
  severity: error
  
closing_brace:
  severity: error
  
closure_parameter_position:
  severity: error
  
colon:
  severity: error
  
comma:
  severity: error
  
compiler_protocol_init:
  severity: error
  
control_statement:
  severity: error
  
cyclomatic_complexity:
  error: 10
  ignores_case_statements: true
  
deployment_target:
  severity: error
  
discarded_notification_center_observer:
  severity: error
  
discouraged_direct_init:
  severity: error
  
duplicate_enum_cases:
  severity: error

duplicate_imports:
  severity: error
  
dynamic_inline:
  severity: error
  
empty_enum_arguments:
  severity: error
  
empty_parameters:
  severity: error
  
empty_parentheses_with_trailing_closure:
  severity: error
  
file_length:
  error: 400
  
for_where:
  severity: error
  
function_body_length:
  error: 20

function_parameter_count:
  error: 5
  
generic_type_name:
  min_length:
    error: 1
    warning: 1
  max_length:
    error: 40
    warning: 40

identifier_name:
  min_length:
    error: 1
    warning: 1
  max_length:
    error: 60
    warning: 60

implicit_getter:
  severity: error
  
inert_defer:
  severity: error
  
is_disjoint:
  severity: error
  
leading_whitespace:
  severity: error
  
legacy_cggeometry_functions:
  severity: error
  
legacy_constant:
  severity: error
  
legacy_constructor:
  severity: error
  
legacy_hashing:
  severity: error
  
legacy_nsgeometry_functions:
  severity: error
  
line_length:
  error: 120
  
mark:
  severity: error
  
multiple_closures_with_trailing_closure:
  severity: error
  
nesting:
  severity: error
  
no_fallthrough_only:
  severity: error
  
notification_center_detachment:
  severity: error
  
nsobject_prefer_isequal:
  severity: error

opening_brace:
  severity: error
  
operator_whitespace:
  severity: error
  
private_over_fileprivate:
  severity: error
  
private_unit_test:
  severity: error
  
protocol_property_accessors_order:
  severity: error
  
reduce_boolean:
  severity: error

redundant_discardable_let:
  severity: error
  
redundant_objc_attribute:
  severity: error
  
redundant_optional_initialization:
  severity: error
  
redundant_set_access_control:
  severity: error
  
redundant_string_enum_value:
  severity: error
  
redundant_void_return:
  severity: error
  
return_arrow_whitespace:
  severity: error
  
shorthand_operator:
  severity: error
  
statement_position:
  severity: error
  
superfluous_disable_command:
  severity: error
  
switch_case_alignment:
  severity: error
  
syntactic_sugar:
  severity: error
  
trailing_comma:
  severity: error
  
trailing_newline:
  severity: error
  
trailing_semicolon:
  severity: error
  
type_body_length:
  error: 200
  
type_name:
  min_length:
    error: 2
    warning: 2
  max_length:
    error: 60
    warning: 60

unneeded_break_in_switch:
  severity: error
  
unused_closure_parameter:
  severity: error
  
unused_control_flow_label:
  severity: error
  
unused_enumerated:
  severity: error
  
unused_optional_binding:
  severity: error
  
unused_setter_value:
  severity: error
  
valid_ibinspectable:
  severity: error
  
vertical_parameter_alignment:
  severity: error
  
vertical_whitespace:
  severity: error
  
void_return:
  severity: error
  
weak_delegate:
  severity: error
  
xctfail_message:
  severity: error


# Opt-In Rules

anyobject_protocol:
  severity: error

array_init: 
  severity: error

closure_spacing: 
  severity: error

collection_alignment: 
  severity: error

contains_over_first_not_nil: 
  severity: error

convenience_type: 
  severity: error

empty_count: 
  severity: error

empty_string: 
  severity: error

empty_xctest_method: 
  severity: error

explicit_init: 
  severity: error

fallthrough: 
  severity: error

fatal_error_message: 
  severity: error

file_name: 
  severity: error

file_types_order:
  severity: error

first_where: 
  severity: error

identical_operands: 
  severity: error

implicit_return: 
  severity: error

joined_default_parameter: 
  severity: error

last_where: 
  severity: error

legacy_multiple:
  severity: error

legacy_random: 
  severity: error

literal_expression_end_indentation: 
  severity: error

modifier_order: 
  severity: error

multiline_arguments:
  severity: error

multiline_function_chains: 
  severity: error

multiline_parameters: 
  severity: error

operator_usage_whitespace: 
  severity: error

overridden_super_call: 
  severity: error

private_action: 
  severity: error

private_outlet: 
  severity: error
  allow_private_set: true

prohibited_super_call: 
  severity: error

reduce_into:
  severity: error

redundant_nil_coalescing: 
  severity: error

redundant_type_annotation: 
  severity: error

single_test_class: 
  severity: error

sorted_first_last: 
  severity: error

static_operator: 
  severity: error

strong_iboutlet: 
  severity: error

toggle_bool: 
  severity: error

trailing_closure: 
  severity: error

unneeded_parentheses_in_closure_argument: 
  severity: error

unused_capture_list:
  severity: error

unused_import: 
  severity: error

unused_private_declaration: 
  severity: error

vertical_parameter_alignment_on_call: 
  severity: error

vertical_whitespace_closing_braces: 
  severity: error

vertical_whitespace_opening_braces: 
  severity: error

xct_specific_matcher: 
  severity: error

yoda_condition: 
  severity: error


# Reporter

reporter: "xcode"
