# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aifcnews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aifcnews
  pod 'ExpandingMenu', '~> 0.3'
  pod 'EasyPeasy'
  pod 'Sugar'
  pod 'MXParallaxHeader'
  pod 'TabPageViewController', :git => 'https://github.com/danabeknar/TabPageViewController.git'
  pod 'PageMenu'
  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher', '~> 3.0'
  pod 'AFDateHelper', '~> 4.2.1'
  pod 'Fabric'
  pod 'Crashlytics'
end
