# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aifcnews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aifcnews
  pod 'EasyPeasy'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  pod 'ReachabilitySwift', '~> 3'
  pod 'BTNavigationDropdownMenu', :git =>'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git'
  pod 'Alamofire', '~> 4.4'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'RealmSwift'
  pod 'DZNEmptyDataSet'
  pod 'SideMenuController'
  pod 'SWXMLHash', '~> 4.0.0'
  pod 'SwiftWebVC'
  pod 'AFDateHelper', '~> 4.2.4'
end
